# Automata Nexus RPi5 SSD Optimizations Configuration

[system]
# Raspberry Pi 5 specific settings
cpu_governor = "performance"
cpu_cores = 4
ram_gb = 8
storage_type = "nvme_ssd"
storage_path = "/mnt/ssd"

[database]
# SQLite optimizations for NVMe SSD
db_path = "/mnt/ssd/automata-nexus/data/metrics.db"
cache_size_mb = 100  # Increased from 10MB
mmap_size_gb = 1     # Memory-mapped I/O
page_size = 4096     # Match SSD page size
journal_mode = "wal"
synchronous = "normal"  # Faster writes on SSD
temp_store = "memory"
wal_autocheckpoint = 10000
busy_timeout_ms = 30000

# Retention settings (expanded for SSD capacity)
retention_days = 30      # Increased from 7
metrics_batch_size = 5000  # Larger batches
vacuum_schedule = "weekly"

[cache]
# Redis cache configuration
enabled = true
host = "127.0.0.1"
port = 6379
max_memory_gb = 1
eviction_policy = "allkeys-lru"
persistence_enabled = true
save_intervals = ["900 1", "300 10", "60 10000"]

[performance]
# Thread pool settings
worker_threads = 8  # 2x CPU cores
async_runtime_threads = 4
sensor_polling_threads = 4

# I/O settings
io_scheduler = "mq-deadline"
read_ahead_kb = 256
nr_requests = 512

# Memory settings
heap_size_mb = 2048
stack_size_mb = 8
huge_pages_enabled = true

[monitoring]
# Sampling rates (Hz)
vibration_sampling_rate = 100  # High-speed vibration
analog_sampling_rate = 10      # 0-10V inputs
digital_sampling_rate = 1      # Digital I/O
logic_execution_rate = 10      # Logic engine

# Buffer sizes
sensor_buffer_size = 10000
metric_buffer_size = 50000
event_buffer_size = 5000

[networking]
# Network optimizations
tcp_nodelay = true
keepalive_enabled = true
keepalive_interval_s = 30
socket_buffer_size_kb = 256

# WebSocket settings
ws_compression = true
ws_max_connections = 100
ws_ping_interval_s = 30

[logging]
# Logging configuration
log_level = "info"
log_path = "/mnt/ssd/automata-nexus/logs"
max_log_size_mb = 100
max_log_files = 10
compression_enabled = true

# Performance logging
perf_log_enabled = true
perf_log_interval_s = 60
metrics_export_enabled = true

[backup]
# Automated backup settings
enabled = true
backup_path = "/mnt/ssd/automata-nexus/backups"
schedule = "daily"
time = "02:00"
retention_days = 30
compression = "gzip"
compression_level = 6

# Remote backup (optional)
remote_enabled = false
remote_type = "s3"  # or "rsync", "rclone"
remote_path = "s3://backup-bucket/automata-nexus/"

[security]
# Security settings
ssl_enabled = true
ssl_cert_path = "/mnt/ssd/automata-nexus/certs/cert.pem"
ssl_key_path = "/mnt/ssd/automata-nexus/certs/key.pem"
auth_enabled = true
session_timeout_minutes = 480
max_login_attempts = 5

[hardware]
# Hardware acceleration
gpio_dma_enabled = true
i2c_baudrate = 400000  # 400kHz fast mode
spi_speed_mhz = 10

# Sequent Microsystems boards
megabas_stack_addresses = [0, 1, 2, 3, 4, 5, 6, 7]
relay16_stack_addresses = [0, 1, 2, 3, 4, 5, 6, 7]
relay8_stack_addresses = [0, 1, 2, 3, 4, 5, 6, 7]
univin16_stack_addresses = [0, 1, 2, 3, 4, 5, 6, 7]
uout16_stack_addresses = [0, 1, 2, 3, 4, 5, 6, 7]

[features]
# Feature flags
bms_integration = true
vibration_monitoring = true
refrigerant_diagnostics = true
predictive_maintenance = true
cloud_sync = false
edge_computing = true
machine_learning = false

[development]
# Development settings
debug_mode = false
profiling_enabled = false
trace_enabled = false
mock_sensors = false